### PR TITLE
Update plugin description

### PR DESCRIPTION
**Pull request by mjulian**

### CODE REVIEW

**Comment by mattyjones** [comment]
@calebhailey @mjulian  Looks good.

I like the fact they that are specific but still somewhat general so we don't have to modify them continuously.

**Comment by mjulian** [comment]
@mattyjones Thanks. The specific-but-general is mostly accidental (there's not much to this plugin). I think it's going to be tough to keep that pattern for many plugins: there's a difficult balance to find between having enough text to be useful, but not too much that it's overly verbose. I think we should rely on plugin authors ensuring the description is up-to-date when new capabilities are added.

**Comment by mattyjones** [comment]
@mjulian   I agree, but that is tough.  We are trying to enfore authors to also maintain the CHANGELOG as well.  Adding this to the list of stuff needed to submit a PR is irksome.

I DO agree it should be done for the betterment of the community as a whole though, enforcing it is another thing entirely ;)

**Comment by calebhailey** [comment]
This is great, thanks @mjulian!

**Pull request merged**
