### PR TITLE
Update check-haproxy.rb - comapre sessions to slim, not to smax

### PR DESCRIPTION
**Pull request by jindraj**
change backends services sessions check comparison to slim instead of smax. Smax is maximum since haproxy start.

## Pull Request Checklist

#39 

#### General

- [x] Update Changelog following the conventions laid out on [Our CHANGELOG Guidelines ](https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md)

- [x] Update README with any necessary configuration snippets

- [x] Binstubs are created if needed

- [x] RuboCop passes

- [x] Existing tests pass

### CODE REVIEW

**Comment by jspaleta** [comment]
Hey!
Can you rebase on current master. we have a conflict now due to the robucop changes

**Comment by jspaleta** [comment]
Also, I think the patch needs to go further there are other usages of smax that probably should be slim

**Comment by jspaleta** [comment]
I take that last comment back. the remaining smax refs are just informational in the check output.

This looks good.. we just need to fix the conflict with master now

**Comment by jspaleta** [comment]
i was able to resolve the conflict...  we should be able to merge this in and get it into the major release coming out to support Bonsai assets as well

**Comment by jindraj** [comment]
I'm sorry, I was AFK during the weekend. Thank you for merging the PR. I'm also closing the related issue #39

**Pull request merged**
